const express = require('express');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const cors = require('cors');
require('dotenv/config');
const fileUpload = require('express-fileupload');

const app = express();
const port = process.env.PORT || 4001;

const router = require('./src/router');
const prisma = require('./src/config/db.config');

// middlewares
app.use(express.static('public'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(cors());

app.use(fileUpload({ createParentPath: 'public' }));

app.use(router);

// app.get('/insert', async (req, res, next) => {
//     await prisma.tbl_profile.createMany({
//         data: [
//             {
//                 'employeeID': 10,
//                 'RFID': '010',
//                 'employee_name': 'Quia',
//                 'DOB': new Date('2023-10-02'),
//                 'NRC': '၅/ဘတလ(နိုင်)၉၆၇၄၅၄',
//                 'nation': 'Et proident corpori',
//                 'religion': 'Neque exercitation d',
//                 'father_name': 'Suki Carey',
//                 'education': 'Exercitationem qui e',
//                 'experience': 'Maiores eum dolore m',
//                 'last_occupation': 'Praesentium sit temp',
//                 'permanent_address': 'Provident et aut do',
//                 'current_address': 'Laboris pariatur Iu',
//                 'phone_number': '+1 (795) 747-5316',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),

//                 'labor_registration_number': '125',
//                 'social_security_number': '433',
//                 'profile_image': null,
//                 'married': false,
//             },
//             {
//                 'employeeID': 5,
//                 'RFID': '005',
//                 'employee_name': 'Earum',
//                 'DOB': new Date('2023-10-02'),
//                 'NRC': '၃/ဖအန(နိုင်)၃၄၅၅၆၇',
//                 'nation': 'At reprehenderit sit',
//                 'religion': 'Placeat quidem libe',
//                 'father_name': 'Mufutau Bass',
//                 'education': 'Fuga Aut dolor ipsa',
//                 'experience': 'Ipsam ut quos eos i',
//                 'last_occupation': 'Earum elit neque do',
//                 'permanent_address': 'Voluptatem sint volu',
//                 'current_address': 'Dolor sit illum si',
//                 'phone_number': '+1 (329) 375-4211',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),

//                 'labor_registration_number': '902',
//                 'social_security_number': '212',
//                 'profile_image': null,
//                 'married': true,
//             },
//             {
//                 'employeeID': 3,
//                 'RFID': '003',
//                 'employee_name': 'ပပမွှေး',
//                 'DOB': new Date('1998-02-19'),
//                 'NRC': '၆/မမန(နိုင်)၂၀၉၀၅၃',
//                 'nation': 'ဗမာ',
//                 'religion': 'ဗုဒ္ဓ',
//                 'father_name': 'ဦးမြတ်စိုးကျော်',
//                 'education': 'Fourth Year English Spalization ',
//                 'experience': 'ဆရာမ',
//                 'last_occupation': 'ဆရာမ',
//                 'permanent_address': 'မြိတ်၊ တနင်္သာရီတိုင်း',
//                 'current_address': 'ဗဟန်း၊ ရန်ကုန်',
//                 'phone_number': '09718293479',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),

//                 'labor_registration_number': '123456',
//                 'social_security_number': '123456',
//                 'profile_image': 'image-1696239043903-2498.IMG_0390.jpg',
//                 'married': false,
//             },
//             {
//                 'employeeID': 6,
//                 'RFID': '006',
//                 'employee_name': 'Aute',
//                 'DOB': new Date('2023-10-02'),
//                 'NRC': '၅/ဟမလ(နိုင်)၃၄၅၇၆၅',
//                 'nation': 'Saepe ut laborum Es',
//                 'religion': 'Nostrum et cumque iu',
//                 'father_name': 'Maile Fox',
//                 'education': 'Fugiat tempora nisi ',
//                 'experience': 'Odio non eveniet ex',
//                 'last_occupation': 'Sit cupidatat enim v',
//                 'permanent_address': 'Corporis et magna si',
//                 'current_address': 'Eiusmod qui et ut er',
//                 'phone_number': '+1 (271) 266-7295',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),

//                 'labor_registration_number': '804',
//                 'social_security_number': '553',
//                 'profile_image': null,
//                 'married': true,
//             },
//             {
//                 'employeeID': 2,
//                 'RFID': '002',
//                 'employee_name': 'ကျော်ကျော်',
//                 'DOB': new Date('2004-02-18'),
//                 'NRC': '၁/အဂယ(နိုင်)၂၀၃၉၂၅',
//                 'nation': 'ဗမာ',
//                 'religion': 'ဗုဒ္ဓ',
//                 'father_name': 'ဦးအောင်ကျော်',
//                 'education': 'အထက်တန်းအောင်',
//                 'experience': 'မရှိ',
//                 'last_occupation': 'မရှိ',
//                 'permanent_address': 'dfsasfasfsa',
//                 'current_address': 'sadfasdfasdfasd',
//                 'phone_number': 'asdfasdfasdf',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),

//                 'labor_registration_number': 'asdfsdf',
//                 'social_security_number': 'asdfasfasdfsd',
//                 'profile_image': null,
//                 'married': true,
//             },
//             {
//                 'employeeID': 7,
//                 'RFID': '007',
//                 'employee_name': 'Alias',
//                 'DOB': new Date('2023-10-02'),
//                 'NRC': '၃/ကကရ(နိုင်)၅၇၆၅၃၅',
//                 'nation': 'Tenetur praesentium ',
//                 'religion': 'Nam et consequatur a',
//                 'father_name': 'Naida Gill',
//                 'education': 'Natus vel iste labor',
//                 'experience': 'Repellendus Volupta',
//                 'last_occupation': 'Mollit rerum anim ip',
//                 'permanent_address': 'Et repudiandae vel i',
//                 'current_address': 'Elit enim debitis n',
//                 'phone_number': '+1 (211) 375-4847',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),

//                 'labor_registration_number': '953',
//                 'social_security_number': '239',
//                 'profile_image': null,
//                 'married': false,
//             },
//             {
//                 'employeeID': 8,
//                 'RFID': '008',
//                 'employee_name': 'Aliquam',
//                 'DOB': new Date('2023-10-02'),
//                 'NRC': '၆/မအရ(နိုင်)၅၇၅၃၃၉',
//                 'nation': 'Velit aliquam molest',
//                 'religion': 'Ut magni officiis si',
//                 'father_name': 'Winifred Gallegos',
//                 'education': 'Est at aute eum adip',
//                 'experience': 'Eos mollit sunt in v',
//                 'last_occupation': 'Dignissimos voluptat',
//                 'permanent_address': 'In corporis exceptur',
//                 'current_address': 'Id in magni exercit',
//                 'phone_number': '+1 (683) 279-7858',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),
//                 'labor_registration_number': '719',
//                 'social_security_number': '325',
//                 'profile_image': null,
//                 'married': false,
//             },
//             {
//                 'employeeID': 9,
//                 'RFID': '009',
//                 'employee_name': 'Voluptas',
//                 'DOB': new Date('2023-10-02'),
//                 'NRC': '၈/ဆဖန(နိုင်)၅၆၇၉၉၀',
//                 'nation': 'Sequi ad consequatur',
//                 'religion': 'Laborum Dolor ea ma',
//                 'father_name': 'Bevis Lewis',
//                 'education': 'Quos reprehenderit ',
//                 'experience': 'Quod do tempor volup',
//                 'last_occupation': 'Dolorem minus rerum ',
//                 'permanent_address': 'Vitae aliquam a quia',
//                 'current_address': 'Est et mollit natus',
//                 'phone_number': '+1 (742) 221-2082',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),

//                 'labor_registration_number': '978',
//                 'social_security_number': '87',
//                 'profile_image': 'image-1696239007824-4940.avatar.jpg',
//                 'married': false,
//             },
//             {
//                 'employeeID': 4,
//                 'RFID': '004',
//                 'employee_name': 'ဇော်ဇော်',
//                 'DOB': new Date('1997-08-06'),
//                 'NRC': '၄/မတန(နိုင်)၁၂၃၄၅၆',
//                 'nation': 'ဗမာ',
//                 'religion': 'ဗုဒ္ဓ',
//                 'father_name': 'ဦးအောင်အောင်',
//                 'education': 'အထက်တန်းအောင်',
//                 'experience': 'မရှိ',
//                 'last_occupation': 'မရှိ',
//                 'permanent_address': 'ရန်ကုန်',
//                 'current_address': 'ရန်ကုန်',
//                 'phone_number': '09123456789',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-10-02'),
//                 'labor_registration_number': '123456',
//                 'social_security_number': '123456',
//                 'profile_image': null,
//                 'married': false,
//             },
//             {
//                 'employeeID': 1,
//                 'RFID': '001',
//                 'employee_name': 'ရဲထက်အောင်',
//                 'DOB': new Date('1998-08-24'),
//                 'NRC': '၇/ပခန(နိုင်)၃၇၇၁၈၂',
//                 'nation': 'ဗမာ',
//                 'religion': 'ဗုဒ္ဓ',
//                 'father_name': 'ဦးအောင်မျိုးမြင့်',
//                 'education': 'အထက်တန်းအောင်',
//                 'experience': 'IT Assistance ',
//                 'last_occupation': 'IT Assistance ',
//                 'permanent_address': 'အင်းတကော်၊ ပဲခူး',
//                 'current_address': 'ဗဟန်း၊ ရန်ကုန်',
//                 'phone_number': '09777117139',
//                 'FNRC_img': null,
//                 'BNRC_img': null,
//                 'recommendation_img': null,
//                 'household_chart_img': null,
//                 'employment_date': new Date('2023-05-01'),
//                 'labor_registration_number': '123456',
//                 'social_security_number': '123456',
//                 'profile_image': 'image-1696235432073-6904.IMG_0799.jpg',
//                 'married': false,
//             },
//         ],
//     });

//     console.log('done');
// });

app.listen(port, () => console.log(`Server is running on port ${port}`));
